# OKC Thunder DS&S Technical Assessment

## Import Packages

In [1]:
#Import packages
import pandas as pd
import numpy as np 
import math
import matplotlib as plt

## Import and Read Data

In [2]:
#read shot data csv
shot_data = pd.read_csv("shots_data.csv")
shot_data.head()

     team     x     y  fgmade
0  Team A -23.1   3.5       0
1  Team A   0.0  25.1       1
2  Team A   0.5   1.0       1
3  Team A  -5.6   5.2       0
4  Team A   4.0  14.5       1

## Transform and Clean Data

In [3]:
#Is a 3 point shot 
    #If y is less than 7.8 is x greater or less than 22 feet 
    #If y is greater than 7.8 is distance from 0,0 greater than 23.75 
        #Then either is 3 point shot 
        #If not then is a 2 pointer 
#create a new column on three pointer (true or false) or 1 and 0 idk yet 
shot_data['three_pointer'] = np.where(((shot_data['y'] < 7.8) & ((shot_data['x'] > 22) | (shot_data['x'] < -22)))
                                      | ((shot_data['y'] > 7.8) & (np.sqrt(shot_data['x'] **2 + shot_data['y'] ** 2) > 23.75))
                                      ,1,0)

#corner 3 or not corner 3
shot_data['corner_three'] = np.where(((shot_data['y'] < 7.8) & ((shot_data['x'] > 22) | (shot_data['x'] < -22))),1,0)

#create team A and team B dataframe 
teamA = shot_data[shot_data['team'] == 'Team A']
teamB = shot_data[shot_data['team'] == 'Team B']

In [4]:
teamA.head()

     team     x     y  fgmade  three_pointer  corner_three
0  Team A -23.1   3.5       0              1             1
1  Team A   0.0  25.1       1              1             0
2  Team A   0.5   1.0       1              0             0
3  Team A  -5.6   5.2       0              0             0
4  Team A   4.0  14.5       1              0             0

In [5]:
teamB.head()

       team     x     y  fgmade  three_pointer  corner_three
280  Team B   2.5   6.2       0              0             0
281  Team B   7.4  18.3       1              0             0
282  Team B   1.1   0.1       0              0             0
283  Team B  -1.6  25.6       0              1             0
284  Team B -14.4  21.7       1              1             0

## Final Calculations

In [6]:
#2, Corner 3, Non corner 3, and 3 
    #shots made/shots attempted 
#Twos made
teamATwoMade = teamA.loc[teamA['three_pointer'] == 0, 'fgmade'].sum()
teamATwoAtt = teamA.loc[teamA['three_pointer'] == 0, 'fgmade'].shape[0]
teamATwoPer = teamATwoMade/teamATwoAtt
print('Team A 2 %')
print(teamATwoPer)
teamBTwoMade = teamB.loc[teamB['three_pointer'] == 0, 'fgmade'].sum()
teamBTwoAtt = teamB.loc[teamB['three_pointer'] == 0, 'fgmade'].shape[0]
teamBTwoPer = teamBTwoMade/teamBTwoAtt
print('Team B 2 %')
print(teamBTwoPer)
#Threes made 
teamAThreeMade = teamA.loc[teamA['three_pointer'] == 1, 'fgmade'].sum()
teamAThreeAtt = teamA.loc[teamA['three_pointer'] == 1, 'fgmade'].shape[0]
teamAThreePer = teamAThreeMade/teamAThreeAtt
print('Team A 3 %')
print(teamAThreePer)
teamBThreeMade = teamB.loc[teamB['three_pointer'] == 1, 'fgmade'].sum()
teamBThreeAtt = teamB.loc[teamB['three_pointer'] == 1, 'fgmade'].shape[0]
teamBThreePer = teamBThreeMade/teamBThreeAtt
print('Team B 3 %')
print(teamBThreePer)
#Corner Threes 
teamACRMade = teamA.loc[teamA['corner_three'] == 1, 'fgmade'].sum()
teamACRAtt = teamA.loc[teamA['corner_three'] == 1, 'fgmade'].shape[0]
teamACRPer = teamACRMade/teamACRAtt
print('Team A Corner 3 %')
print(teamACRPer)
teamBCRMade = teamB.loc[teamB['corner_three'] == 1, 'fgmade'].sum()
teamBCRAtt = teamB.loc[teamB['corner_three'] == 1, 'fgmade'].shape[0]
teamBCRPer = teamBCRMade/teamBCRAtt
print('Team B Corner 3 %')
print(teamBCRPer)
#Non Corner Threes
teamAnCRMade = teamA.loc[(teamA['corner_three'] == 0) & (teamA['three_pointer'] == 1), 'fgmade'].sum()
teamAnCRAtt = teamA.loc[(teamA['corner_three'] == 0) & (teamA['three_pointer'] == 1), 'fgmade'].shape[0]
teamAnCRPer = teamAnCRMade/teamAnCRAtt
print('Team A Non Corner 3 %')
print(teamAnCRPer)
teamBnCRMade = teamB.loc[(teamB['corner_three'] == 0) & (teamB['three_pointer'] == 1), 'fgmade'].sum()
teamBnCRAtt = teamB.loc[(teamB['corner_three'] == 0) & (teamB['three_pointer'] == 1), 'fgmade'].shape[0]
teamBnCRPer = teamBnCRMade/teamBnCRAtt
print('Team B Non Corner 3 %')
print(teamBnCRPer)
#efg
    #made + .5(3 made)/attempted
teamAeFg = (teamA['fgmade'].sum() + teamA['three_pointer'].sum()/2)/teamA.shape[0]
print('Team A eFG')
print(teamAeFg)
teamBeFg = (teamB['fgmade'].sum() + teamB['three_pointer'].sum()/2)/teamB.shape[0]
print('Team B eFG')
print(teamBeFg)

Team A 2 %
0.4
Team B 2 %
0.4601226993865031
Team A 3 %
0.33636363636363636
Team B 3 %
0.3418803418803419
Team A Corner 3 %
0.4
Team B Corner 3 %
0.23809523809523808
Team A Non Corner 3 %
0.32222222222222224
Team B Non Corner 3 %
0.3645833333333333
Team A eFG
0.5714285714285714
Team B eFG
0.6196428571428572

## Final Deliverables

In [7]:
print('Question 5')
print((teamA['three_pointer'] == 0).sum()/teamA.shape[0])
print('Question 6')
print(((teamA['corner_three'] == 0) & (teamA['three_pointer'] == 1)).sum()/teamA.shape[0])
print('Question 7')
print((teamA['corner_three'] == 1).sum()/teamA.shape[0])
print('Question 8')
teamATwoMade = teamA.loc[teamA['three_pointer'] == 0, 'fgmade'].sum()
teamATwoAtt = teamA.loc[teamA['three_pointer'] == 0, 'fgmade'].shape[0]
teamATwoPer = teamATwoMade/teamATwoAtt
print(teamATwoPer)
print('Question 9')
teamAnCRMade = teamA.loc[(teamA['corner_three'] == 0) & (teamA['three_pointer'] == 1), 'fgmade'].sum()
teamAnCRAtt = teamA.loc[(teamA['corner_three'] == 0) & (teamA['three_pointer'] == 1), 'fgmade'].shape[0]
teamAnCRPer = (teamAnCRMade + teamAnCRMade/2)/teamAnCRAtt
print(teamAnCRPer)
print('Question 10')
teamACRMade = teamA.loc[teamA['corner_three'] == 1, 'fgmade'].sum()
teamACRAtt = teamA.loc[teamA['corner_three'] == 1, 'fgmade'].shape[0]
teamACRPer = (teamACRMade + teamACRMade/2)/teamACRAtt
print(teamACRPer)

print('Question 11')
print((teamB['three_pointer'] == 0).sum()/teamB.shape[0])
print('Question 12')
print(((teamB['corner_three'] == 0) & (teamB['three_pointer'] == 1)).sum()/teamB.shape[0])
print('Question 13')
print((teamB['corner_three'] == 1).sum()/teamB.shape[0])
print('Question 14')
teamBTwoMade = teamB.loc[teamB['three_pointer'] == 0, 'fgmade'].sum()
teamBTwoAtt = teamB.loc[teamB['three_pointer'] == 0, 'fgmade'].shape[0]
teamBTwoPer = teamBTwoMade/teamBTwoAtt
print(teamBTwoPer)
print('Question 15')
teamBnCRMade = teamB.loc[(teamB['corner_three'] == 0) & (teamB['three_pointer'] == 1), 'fgmade'].sum()
teamBnCRAtt = teamB.loc[(teamB['corner_three'] == 0) & (teamB['three_pointer'] == 1), 'fgmade'].shape[0]
teamBnCRPer = (teamBnCRMade + teamBnCRMade/2)/teamBnCRAtt
print(teamBnCRPer)
print('Question 16')
teamBCRMade = teamB.loc[teamB['corner_three'] == 1, 'fgmade'].sum()
teamBCRAtt = teamB.loc[teamB['corner_three'] == 1, 'fgmade'].shape[0]
teamBCRPer = (teamBCRMade + teamBCRMade/2)/teamBCRAtt
print(teamBCRPer)

Question 5
0.6071428571428571
Question 6
0.32142857142857145
Question 7
0.07142857142857142
Question 8
0.4
Question 9
0.48333333333333334
Question 10
0.6
Question 11
0.5821428571428572
Question 12
0.34285714285714286
Question 13
0.075
Question 14
0.4601226993865031
Question 15
0.546875
Question 16
0.35714285714285715